### ISSUE TITLE
_lzallright.abi3.so: undefined symbol: lzokay$cxxbridge1$new_dict

### ISSUE THREAD

**Issue by D3vil0p3r** [vlaci/lzallright#77]
Once installed the latest commit of `lzallright`, when I import it, I get:
```
>>> import lzallright
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.12/site-packages/lzallright/__init__.py", line 9, in <module>
    from lzallright._lzallright import EResult, InputNotConsumed, LZOCompressor, LZOError
ImportError: /usr/lib/python3.12/site-packages/lzallright/_lzallright.abi3.so: undefined symbol: lzokay$cxxbridge1$new_dict
```

**Comment by D3vil0p3r** [comment]
@vlaci can you give a look to it? I see it has been reported also on Arch AUR package.

**Comment by vlaci** [comment]
Is the issue present on the previous (v0.2.4) version?

**Comment by vlaci** [comment]
Never mind, I see from the AUR link, that the reported had this issue since before the current version was released.

Could you add some reproduction details?
- OS you use
- how did you install `lzallright`
- if you haven't used pip, does `pip install lzallright==0.2.5` work?

**Comment by D3vil0p3r** [comment]
Here the details:
* It occurs also on v0.2.4
* OS: Arch Linux
* I'm packaging a package for Arch Linux different from AUR package that works as:
  ```
    python -m build --wheel --outdir="$startdir/dist"
    pip install \
    --verbose \
    --disable-pip-version-check \
    --no-warn-script-location \
    --ignore-installed \
    --no-compile \
    --no-deps \
    --root="$pkgdir" \
    --prefix=/usr \
    --no-index \
    --find-links="file://$startdir/dist" \
    lzallright
  ```
* I'm not setting any `CXXFLAGS`. Should I do?

**Comment by vlaci** [comment]
Did you try setting the mentioned `options=(!lto)` setting in your PKGBUILD? If you are building with `makepkg` or other derivative in arch, it will set up a bunch of compiler flags for you. Some of it is interfering with the build.

**Comment by D3vil0p3r** [comment]
By setting `!lto` it works correctly. So I don't know what is the issue during the building when `!lto` is not set.

**Comment by vlaci** [comment]
I guess it accidentally removes a symbol during build. You may add `echo LDFLAGS=$LDFLAGS; CXXFLAGS=$CXXFLAGS` in your PKGBUILD to see what is the difference when using `!lto` option.

**Comment by D3vil0p3r** [comment]
I get this when `!lto` is set:
```
LDFLAGS=; CXXFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection         -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -Wp,-D_GLIBCXX_ASSERTIONS -g -ffile-prefix-map=/tmp/makepkg/python-lzallright/src=/usr/src/debug/python-lzallright
```

**Comment by D3vil0p3r** [comment]
So, the difference seems to be `-flto=auto` that could be the cause of the issue.

**Comment by vlaci** [comment]
Does it change anything if you append `-ffat-lto-objects` e.g. by `export CXXFLAGS="$CXXFLAGS -ffat-lto-objects"` to your PKGBUILD

**Comment by D3vil0p3r** [comment]
By setting that `export` it works without `!lto`.
